# Site settings
title: Denis Gagnon
description: > # this means to ignore newlines until "baseurl:"
  Physicist specialized in numerical modeling and computer enthusiast
baseurl: ""
url: "http://denisgagnon.info"
twitter_username: madgagnon
github_username:  McNoggins

# Build settings
markdown: kramdown
